export const UP_ICT_FACULTY = [
  {
    email: 'rachen.su@up.ac.th',
    name_en: 'Rachen Sookmuang',
    name_th: 'ราเชนทร์ สุขม่วง',
    position: 'ประธานหลักสูตร / อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Computer Graphics and Multimedia',
  },
  {
    email: 'ratanapat.su@up.ac.th',
    name_en: 'Ratanapat Suchat',
    name_th: 'รตนพรรษ สุชาติ',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'w0vNVh8AAAAJ',
    scopus_id: '57202949045',
    department: 'Computer Graphics and Multimedia',
  },
  {
    email: 'nakharet.ch@up.ac.th',
    name_en: 'nakharet chaikaew',
    name_th: 'นคเรศ ชัยแก้ว',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'hSZaKRAAAAAJ',
    scopus_id: null,
    department: 'Computer Graphics and Multimedia',
  },
  {
    email: 'suleeporn.ka@up.ac.th',
    name_en: 'Suleeporn Kamchompoo',
    name_th: 'ศุลีพร คำชมภู',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'NZ3ZSWoAAAAJ',
    scopus_id: null,
    department: 'Computer Graphics and Multimedia',
  },
  {
    email: 'pakawad.bu@up.ac.th',
    name_en: 'Pakawad Butsri',
    name_th: 'ภควัส บุตรศรี',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Computer Graphics and Multimedia',
  },
  {
    email: 'wisoot.ka@up.ac.th',
    name_en: 'wisoot kaenmueang',
    name_th: 'วิสูตร แก่นเมือง',
    position: 'อาจารย์',
    scholar_id: 'UImKTowAAAAJ',
    scopus_id: '57223964502',
    department: 'Computer Graphics and Multimedia',
  },
  {
    email: 'apiwat.pu@up.ac.th',
    name_en: 'apiwat puntatong',
    name_th: 'อภิวัฒน์ ปันทะธง',
    position: 'อาจารย์',
    scholar_id: 'X2VbOl8AAAAJ',
    scopus_id: '57223977107',
    department: 'Computer Graphics and Multimedia',
  },
  {
    email: 'thapanapong.sa@up.ac.th',
    name_en: 'Thapanapong Sararat',
    name_th: 'ฐาปนพงศ์ สารรัตน์',
    position: 'อาจารย์',
    scholar_id: 'BFmk2WkAAAAJ',
    scopus_id: '58940183700',
    department: 'Computer Graphics and Multimedia',
  },
  {
    email: 'wanvajee.kh@up.ac.th',
    name_en: 'Wanvajee Krutnoi',
    name_th: 'วรรณวจี ครุธน้อย',
    position: 'ผู้ช่วยสอน',
    scholar_id: null,
    scopus_id: null,
    department: 'Computer Graphics and Multimedia',
  },
  {
    email: 'jirawat.su@up.ac.th',
    name_en: 'Jirawat sookkaew',
    name_th: 'จิรวัฒน์ สุขแก้ว',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'bkS6RFAAAAAJ',
    scopus_id: '57223960981',
    department: 'Computer Graphics and Multimedia',
  },
  {
    email: 'supan.to@up.ac.th',
    name_en: 'supan tongphet',
    name_th: 'สุพรรณ์ ทองเพชร',
    position: 'ประธานหลักสูตร / อาจารย์',
    scholar_id: 'j8NfztMAAAAJ',
    scopus_id: '57216979498',
    department: 'Digital Business',
  },
  {
    email: 'thitirath.ch@up.ac.th',
    name_en: 'Thitirath Cheowsuwan',
    name_th: 'ฐิติรัตน์ เชี่ยวสุวรรณ',
    position: 'รองศาสตราจารย์ / รองอธิการบดี',
    scholar_id: null,
    scopus_id: '57208544988',
    department: 'Digital Business',
  },
  {
    email: 'kaewarin.ja@up.ac.th',
    name_en: 'kaewarin jandum',
    name_th: 'เกวรินทร์ จันทร์ดำ',
    position: 'อาจารย์ / รองคณบดี',
    scholar_id: 'upsWdfgAAAAJ',
    scopus_id: '57191413506',
    department: 'Digital Business',
  },
  {
    email: 'napa.ra@up.ac.th',
    name_en: 'Napa Rachata',
    name_th: 'นภา ราชตา',
    position: 'ผู้ช่วยศาสตราจารย์ / รองคณบดี',
    scholar_id: 'EwzRbK4AAAAJ',
    scopus_id: '26654356700',
    department: 'Digital Business',
  },
  {
    email: 'krittika.ka@up.ac.th',
    name_en: 'krittika kantawong',
    name_th: 'กฤติกา กันทวงค์',
    position: 'ผู้ช่วยศาสตราจารย์ / ผู้ช่วยคณบดี',
    scholar_id: 'bKG2lWkAAAAJ',
    scopus_id: '57194213179',
    department: 'Digital Business',
  },
  {
    email: 'pratya.nu@up.ac.th',
    name_en: 'Pratya Nuankaew',
    name_th: 'ปรัชญา นวนแก้ว',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: '5nYO_-cAAAAJ',
    scopus_id: '56426447600',
    department: 'Digital Business',
  },
  {
    email: 'thanapon.th@up.ac.th',
    name_en: 'Thanapon Thiradathanaphatdecha',
    name_th: 'ธนภณ ถิรดาธนภัทรเดชา',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57194218003',
    department: 'Digital Business',
  },
  {
    email: 'surinthip.sa@up.ac.th',
    name_en: 'Surinthip Sakphuowadol',
    name_th: 'สุรินทร์ทิพ ศักดิ์ภูวดล',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57205660007',
    department: 'Digital Business',
  },
  {
    email: 'sudarat.ar@up.ac.th',
    name_en: 'Sudarat Aht-harn',
    name_th: 'สุดารัตน์ อาจหาญ',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57208549157',
    department: 'Digital Business',
  },
  {
    email: 'pipatpong.sa@up.ac.th',
    name_en: 'Pipatpong Sae-phu',
    name_th: 'พิพัฒน์พงษ์ แซ่พู่',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57406775300',
    department: 'Digital Business',
  },
  {
    email: 'sathien.hu@up.ac.th',
    name_en: 'SATHIEN HUNTA',
    name_th: 'เสถียร หันตา',
    position: 'ประธานหลักสูตร / อาจารย์',
    scholar_id: 'OtIA5PEAAAAJ',
    scopus_id: '25031508600',
    department: 'Digital Business',
  },
  {
    email: 'rattanawadee.pa@up.ac.th',
    name_en: 'Rattanawadee Panthong',
    name_th: 'รัตนาวดี พานทอง',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'szUHb4wAAAAJ',
    scopus_id: '57188876042',
    department: 'Digital Business',
  },
  {
    email: 'sakkayaphop.pr@up.ac.th',
    name_en: 'Sakkayaphop Pravesjit',
    name_th: 'ศกยภพ ประเวทจิตร์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'mKETtsEAAAAJ',
    scopus_id: '49864260100',
    department: 'Digital Business',
  },
  {
    email: 'thidapath.an@up.ac.th',
    name_en: 'Thidapath Anucharn',
    name_th: 'ธิดาภัทร อนุชาญ',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'Cn5DYBUAAAAJ',
    scopus_id: '57194180287',
    department: 'Digital Business',
  },
  {
    email: 'yeunyong.ka@up.ac.th',
    name_en: 'Yeunyong Kantanet',
    name_th: 'ยืนยง กันทะเนตร',
    position: 'อาจารย์',
    scholar_id: 'kOv6vpUAAAAJ',
    scopus_id: '59679847100',
    department: 'Digital Business',
  },
  {
    email: 'sanchai.ye@up.ac.th',
    name_en: 'Sanchai Yeewiyom',
    name_th: 'สัณห์ชัย หยีวิยม',
    position: 'อาจารย์',
    scholar_id: 'PJ9aDnEAAAAJ',
    scopus_id: null,
    department: 'Digital Business',
  },
  {
    email: 'nattapong.ka@up.ac.th',
    name_en: 'Natdanai Kamkhad',
    name_th: 'ณัฐดนัย คำขาด',
    position: 'อาจารย์',
    scholar_id: 'qTB5DqsAAAAJ',
    scopus_id: '57216207659',
    department: 'Digital Business',
  },
  {
    email: 'rattasak.pe@up.ac.th',
    name_en: 'Rattasak Pengchata',
    name_th: 'รัตน์ธศักดิ์ เพ็งชะตา',
    position: 'อาจารย์',
    scholar_id: 'e_0l4DYAAAAJ',
    scopus_id: '57302561700',
    department: 'Digital Business',
  },
  {
    email: 'thaksaorn.jo@up.ac.th',
    name_en: 'Thaksaorn Jommanop',
    name_th: 'ทักษอร จอมมานพ',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Digital Business',
  },
  {
    email: 'sathien.hu@up.ac.th',
    name_en: 'SATHIEN HUNTA',
    name_th: 'เสถียร หันตา',
    position: 'ประธานหลักสูตร / อาจารย์',
    scholar_id: 'OtIA5PEAAAAJ',
    scopus_id: '25031508600',
    department: 'Information Technology',
  },
  {
    email: 'rattanawadee.pa@up.ac.th',
    name_en: 'Rattanawadee Panthong',
    name_th: 'รัตนาวดี พานทอง',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'szUHb4wAAAAJ',
    scopus_id: '57188876042',
    department: 'Information Technology',
  },
  {
    email: 'sakkayaphop.pr@up.ac.th',
    name_en: 'Sakkayaphop Pravesjit',
    name_th: 'ศกยภพ ประเวทจิตร์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'mKETtsEAAAAJ',
    scopus_id: '49864260100',
    department: 'Information Technology',
  },
  {
    email: 'thidapath.an@up.ac.th',
    name_en: 'Thidapath Anucharn',
    name_th: 'ธิดาภัทร อนุชาญ',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'Cn5DYBUAAAAJ',
    scopus_id: '57194180287',
    department: 'Information Technology',
  },
  {
    email: 'yeunyong.ka@up.ac.th',
    name_en: 'Yeunyong Kantanet',
    name_th: 'ยืนยง กันทะเนตร',
    position: 'อาจารย์',
    scholar_id: 'kOv6vpUAAAAJ',
    scopus_id: '59679847100',
    department: 'Information Technology',
  },
  {
    email: 'sanchai.ye@up.ac.th',
    name_en: 'Sanchai Yeewiyom',
    name_th: 'สัณห์ชัย หยีวิยม',
    position: 'อาจารย์',
    scholar_id: 'PJ9aDnEAAAAJ',
    scopus_id: null,
    department: 'Information Technology',
  },
  {
    email: 'nattapong.ka@up.ac.th',
    name_en: 'Natdanai Kamkhad',
    name_th: 'ณัฐดนัย คำขาด',
    position: 'อาจารย์',
    scholar_id: 'qTB5DqsAAAAJ',
    scopus_id: '57216207659',
    department: 'Information Technology',
  },
  {
    email: 'rattasak.pe@up.ac.th',
    name_en: 'Rattasak Pengchata',
    name_th: 'รัตน์ธศักดิ์ เพ็งชะตา',
    position: 'อาจารย์',
    scholar_id: 'e_0l4DYAAAAJ',
    scopus_id: '57302561700',
    department: 'Information Technology',
  },
  {
    email: 'thaksaorn.jo@up.ac.th',
    name_en: 'Thaksaorn Jommanop',
    name_th: 'ทักษอร จอมมานพ',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Information Technology',
  },
  {
    email: 'jiraporn.ko@up.ac.th',
    name_en: 'Jiraporn Kulsoontornrat',
    name_th: 'จิราพร กุลสุนทรรัตน์',
    position: 'ผู้ช่วยศาสตราจารย์ / ประธานหลักสูตร',
    scholar_id: 'gsy7MH0AAAAJ',
    scopus_id: '57328453100',
    department: 'Information Technology',
  },
  {
    email: 'nakarin.ch@up.ac.th',
    name_en: 'Nakarin Chaikaew',
    name_th: 'นครินทร์ ชัยแก้ว',
    position: 'ผู้ช่วยศาสตราจารย์ / รองคณบดี',
    scholar_id: 'KfBBb-UAAAAJ',
    scopus_id: '27967464000',
    department: 'Information Technology',
  },
  {
    email: 'boonsiri.su@up.ac.th',
    name_en: 'Boonsiri Suksombat',
    name_th: 'บุญศิริ สุขพร้อมสรรพ์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: null,
    scopus_id: '57208738242',
    department: 'Information Technology',
  },
  {
    email: 'niti.ia@up.ac.th',
    name_en: 'Niti Iamchuen',
    name_th: 'นิติ เอี่ยมชื่น',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'Hnbe6VkAAAAJ',
    scopus_id: '57202941262',
    department: 'Information Technology',
  },
  {
    email: 'wipop.pa@up.ac.th',
    name_en: 'wipop paengwangthong',
    name_th: 'วิภพ แพงวังทอง',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: '3UtScF0AAAAJ',
    scopus_id: '55349430900',
    department: 'Information Technology',
  },
  {
    email: 'phaisarn.je@up.ac.th',
    name_en: 'Phaisarn Jeefoo',
    name_th: 'ไพศาล จี้ฟู',
    position: 'รองศาสตราจารย์',
    scholar_id: 'BRJXF00AAAAJ',
    scopus_id: '36959322700',
    department: 'Information Technology',
  },
  {
    email: 'sawarin.le@up.ac.th',
    name_en: 'Sawarin Roekyusuk',
    name_th: 'สวรินทร์ ฤกษ์อยู่สุข',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '55789747500',
    department: 'Information Technology',
  },
  {
    email: 'chutpong.pa@up.ac.th',
    name_en: 'Chatchaphong Phachanaphan',
    name_th: 'ชัชพงศ์ ภาชนะพรรณ์',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Information Technology',
  },
  {
    email: 'wongpanya.nu@up.ac.th',
    name_en: '\'Wongpanya Nuankaew',
    name_th: 'วงษ์ปัญญา นวนแก้ว',
    position: 'ผู้ช่วยศาสตราจารย์ / ประธานหลักสูตร',
    scholar_id: 'pWRnha8AAAAJ',
    scopus_id: '57193735880',
    department: 'Information Technology',
  },
  {
    email: 'surangkana.ra@up.ac.th',
    name_en: '\'Surangkana Rawungyot',
    name_th: 'สุรางคนา ระวังยศ',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'ONrwXPcAAAAJ',
    scopus_id: '56247320800',
    department: 'Information Technology',
  },
  {
    email: 'worrakit.sa@up.ac.th',
    name_en: 'worrakit sanpote',
    name_th: 'วรกฤต แสนโภชน์',
    position: 'อาจารย์',
    scholar_id: 'd5XfUKoAAAAJ',
    scopus_id: null,
    department: 'Information Technology',
  },
  {
    email: 'thanawat.sa@up.ac.th',
    name_en: 'Thanawat Sae-eab',
    name_th: 'ธนวัฒน์ แซ่เอียบ',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Information Technology',
  },
  {
    email: 'kiattikul.so@up.ac.th',
    name_en: 'Kiattikul Suksomsathan',
    name_th: 'เกียรติกุล สุขสมสถาน',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '56109204000',
    department: 'Information Technology',
  },
  {
    email: 'thammarat.th@up.ac.th',
    name_en: 'Thammarat Thamma',
    name_th: 'ธรรมรัตน์ ธรรมา',
    position: 'อาจารย์',
    scholar_id: '-M6OQm4AAAAJ',
    scopus_id: null,
    department: 'Information Technology',
  },
  {
    email: 'paweena.un@up.ac.th',
    name_en: 'Paweena Unlee',
    name_th: 'ปวีณา อุ่นลี',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Information Technology',
  },
  {
    email: 'sarit.pr@up.ac.th',
    name_en: 'Sarit Promthep',
    name_th: 'ศริทธิ์ พร้อมเทพ',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Information Technology',
  },
  {
    email: 'sakpan.da@up.ac.th',
    name_en: 'Sakpan Dangmanee',
    name_th: 'ศักดิ์พันธุ์ แดงมณี',
    position: 'อาจารย์',
    scholar_id: 'AeOY2nYAAAAJ',
    scopus_id: '57223979059',
    department: 'Information Technology',
  },
  {
    email: 'noppadon.yo@up.ac.th',
    name_en: 'Noppadon Yosboonruang',
    name_th: 'นพดล ยศบุญเรือง',
    position: 'ผู้ช่วยศาสตราจารย์ / ประธานหลักสูตร',
    scholar_id: '2K_AJKUAAAAJ',
    scopus_id: null,
    department: 'Information Technology',
  },
  {
    email: 'kanokwatt.sh@up.ac.th',
    name_en: 'KANOKWATT SHIANGJEN',
    name_th: 'กนกวรรธน์ เซี่ยงเจ็น',
    position: 'อาจารย์',
    scholar_id: 'w2LATP4AAAAJ',
    scopus_id: '57120194100',
    department: 'Information Technology',
  },
  {
    email: 'sulawan.yo@up.ac.th',
    name_en: 'Sulawan Yotthanoo',
    name_th: 'สุลาวัลย์ ยศธนู',
    position: 'อาจารย์',
    scholar_id: 'oK0RgRcAAAAJ',
    scopus_id: null,
    department: 'Information Technology',
  },
  {
    email: 'jiraporn.ko@up.ac.th',
    name_en: 'Jiraporn Kulsoontornrat',
    name_th: 'จิราพร กุลสุนทรรัตน์',
    position: 'ผู้ช่วยศาสตราจารย์ / ประธานหลักสูตร',
    scholar_id: 'gsy7MH0AAAAJ',
    scopus_id: '57328453100',
    department: 'Geoinformatics',
  },
  {
    email: 'nakarin.ch@up.ac.th',
    name_en: 'Nakarin Chaikaew',
    name_th: 'นครินทร์ ชัยแก้ว',
    position: 'ผู้ช่วยศาสตราจารย์ / รองคณบดี',
    scholar_id: 'KfBBb-UAAAAJ',
    scopus_id: '27967464000',
    department: 'Geoinformatics',
  },
  {
    email: 'boonsiri.su@up.ac.th',
    name_en: 'Boonsiri Suksombat',
    name_th: 'บุญศิริ สุขพร้อมสรรพ์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: null,
    scopus_id: '57208738242',
    department: 'Geoinformatics',
  },
  {
    email: 'niti.ia@up.ac.th',
    name_en: 'Niti Iamchuen',
    name_th: 'นิติ เอี่ยมชื่น',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'Hnbe6VkAAAAJ',
    scopus_id: '57202941262',
    department: 'Geoinformatics',
  },
  {
    email: 'wipop.pa@up.ac.th',
    name_en: 'wipop paengwangthong',
    name_th: 'วิภพ แพงวังทอง',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: '3UtScF0AAAAJ',
    scopus_id: '55349430900',
    department: 'Geoinformatics',
  },
  {
    email: 'phaisarn.je@up.ac.th',
    name_en: 'Phaisarn Jeefoo',
    name_th: 'ไพศาล จี้ฟู',
    position: 'รองศาสตราจารย์',
    scholar_id: 'BRJXF00AAAAJ',
    scopus_id: '36959322700',
    department: 'Geoinformatics',
  },
  {
    email: 'sawarin.le@up.ac.th',
    name_en: 'Sawarin Roekyusuk',
    name_th: 'สวรินทร์ ฤกษ์อยู่สุข',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '55789747500',
    department: 'Geoinformatics',
  },
  {
    email: 'chutpong.pa@up.ac.th',
    name_en: 'Chatchaphong Phachanaphan',
    name_th: 'ชัชพงศ์ ภาชนะพรรณ์',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Geoinformatics',
  },
  {
    email: 'wongpanya.nu@up.ac.th',
    name_en: '\'Wongpanya Nuankaew',
    name_th: 'วงษ์ปัญญา นวนแก้ว',
    position: 'ผู้ช่วยศาสตราจารย์ / ประธานหลักสูตร',
    scholar_id: 'pWRnha8AAAAJ',
    scopus_id: '57193735880',
    department: 'Geoinformatics',
  },
  {
    email: 'surangkana.ra@up.ac.th',
    name_en: '\'Surangkana Rawungyot',
    name_th: 'สุรางคนา ระวังยศ',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'ONrwXPcAAAAJ',
    scopus_id: '56247320800',
    department: 'Geoinformatics',
  },
  {
    email: 'worrakit.sa@up.ac.th',
    name_en: 'worrakit sanpote',
    name_th: 'วรกฤต แสนโภชน์',
    position: 'อาจารย์',
    scholar_id: 'd5XfUKoAAAAJ',
    scopus_id: null,
    department: 'Geoinformatics',
  },
  {
    email: 'thanawat.sa@up.ac.th',
    name_en: 'Thanawat Sae-eab',
    name_th: 'ธนวัฒน์ แซ่เอียบ',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Geoinformatics',
  },
  {
    email: 'kiattikul.so@up.ac.th',
    name_en: 'Kiattikul Suksomsathan',
    name_th: 'เกียรติกุล สุขสมสถาน',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '56109204000',
    department: 'Geoinformatics',
  },
  {
    email: 'thammarat.th@up.ac.th',
    name_en: 'Thammarat Thamma',
    name_th: 'ธรรมรัตน์ ธรรมา',
    position: 'อาจารย์',
    scholar_id: '-M6OQm4AAAAJ',
    scopus_id: null,
    department: 'Geoinformatics',
  },
  {
    email: 'paweena.un@up.ac.th',
    name_en: 'Paweena Unlee',
    name_th: 'ปวีณา อุ่นลี',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Geoinformatics',
  },
  {
    email: 'sarit.pr@up.ac.th',
    name_en: 'Sarit Promthep',
    name_th: 'ศริทธิ์ พร้อมเทพ',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Geoinformatics',
  },
  {
    email: 'sakpan.da@up.ac.th',
    name_en: 'Sakpan Dangmanee',
    name_th: 'ศักดิ์พันธุ์ แดงมณี',
    position: 'อาจารย์',
    scholar_id: 'AeOY2nYAAAAJ',
    scopus_id: '57223979059',
    department: 'Geoinformatics',
  },
  {
    email: 'noppadon.yo@up.ac.th',
    name_en: 'Noppadon Yosboonruang',
    name_th: 'นพดล ยศบุญเรือง',
    position: 'ผู้ช่วยศาสตราจารย์ / ประธานหลักสูตร',
    scholar_id: '2K_AJKUAAAAJ',
    scopus_id: null,
    department: 'Geoinformatics',
  },
  {
    email: 'kanokwatt.sh@up.ac.th',
    name_en: 'KANOKWATT SHIANGJEN',
    name_th: 'กนกวรรธน์ เซี่ยงเจ็น',
    position: 'อาจารย์',
    scholar_id: 'w2LATP4AAAAJ',
    scopus_id: '57120194100',
    department: 'Geoinformatics',
  },
  {
    email: 'sulawan.yo@up.ac.th',
    name_en: 'Sulawan Yotthanoo',
    name_th: 'สุลาวัลย์ ยศธนู',
    position: 'อาจารย์',
    scholar_id: 'oK0RgRcAAAAJ',
    scopus_id: null,
    department: 'Geoinformatics',
  },
  {
    email: 'kemmawadee.pr@up.ac.th',
    name_en: 'Kemmawadee Preedalikit',
    name_th: 'เขมวดี ปรีดาลิขิต',
    position: 'อาจารย์',
    scholar_id: 'CnkxqpgAAAAJ',
    scopus_id: null,
    department: 'Geoinformatics',
  },
  {
    email: 'piyada.ph@up.ac.th',
    name_en: 'Piyada Phrueksawatnon',
    name_th: 'ปิยดา พฤกสวัสดิ์นนท์',
    position: 'อาจารย์',
    scholar_id: 'vGckr9gAAAAJ',
    scopus_id: null,
    department: 'Geoinformatics',
  },
  {
    email: 'satsayamon.su@up.ac.th',
    name_en: 'satsayamon suksaengrakcharoen',
    name_th: 'ศัสยมน สุขแสงรักษ์เจริญ',
    position: 'อาจารย์',
    scholar_id: 'YgHiTT0AAAAJ',
    scopus_id: null,
    department: 'Geoinformatics',
  },
  {
    email: 'ruttana.ri@up.ac.th',
    name_en: 'Rattana Prommai',
    name_th: 'รัตนา พรมใหม่',
    position: 'อาจารย์',
    scholar_id: 'dorztZoAAAAJ',
    scopus_id: null,
    department: 'Geoinformatics',
  },
  {
    email: 'apiwat.wi@up.ac.th',
    name_en: 'Apiwat Wittayarat',
    name_th: 'อภิวัฒน์ วิทยารัฐ',
    position: 'ประธานหลักสูตร / อาจารย์',
    scholar_id: null,
    scopus_id: '57215270571',
    department: 'Geoinformatics',
  },
  {
    email: 'pornthep.ro@up.ac.th',
    name_en: 'Pornthep Rojanavasu',
    name_th: 'พรเทพ โรจนวสุ',
    position: 'ผู้ช่วยศาสตราจารย์ / คณบดี',
    scholar_id: 'pGxD1nkAAAAJ',
    scopus_id: '24464512600',
    department: 'Geoinformatics',
  },
  {
    email: 'jirabhorn.ch@up.ac.th',
    name_en: 'jirabhorn chaiwongsai',
    name_th: 'จิราพร ไชยวงศ์สาย',
    position: 'ผู้ช่วยศาสตราจารย์ / รองคณบดี',
    scholar_id: 'uSFP9soAAAAJ',
    scopus_id: '26643827900',
    department: 'Geoinformatics',
  },
  {
    email: 'bowonsak.sr@up.ac.th',
    name_en: 'Bowonsak Srisungsitthisanti',
    name_th: 'บวรศักดิ์ ศรีสังสิทธิสันติ',
    position: 'ผู้ช่วยศาสตราจารย์ / ผู้ช่วยคณบดี',
    scholar_id: 'AOHQFg8AAAAJ',
    scopus_id: '56021717400',
    department: 'Geoinformatics',
  },
  {
    email: 'sakorn.me@up.ac.th',
    name_en: 'Sakorn Mekruksavanich',
    name_th: 'สาคร เมฆรักษาวนิช',
    position: 'รองศาสตราจารย์',
    scholar_id: 'BElkl-MAAAAJ',
    scopus_id: '35174894700',
    department: 'Geoinformatics',
  },
  {
    email: 'thana.ud@up.ac.th',
    name_en: 'Thana Udomsripaiboon',
    name_th: 'ธนา อุดมศรีไพบูลย์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'HAAwwFIAAAAJ',
    scopus_id: '15926581200',
    department: 'Geoinformatics',
  },
  {
    email: 'wattanapong.su@up.ac.th',
    name_en: 'Wattanapong Suttapak',
    name_th: 'วัฒนพงศ์ สุทธภักดิ์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'A0mVNt4AAAAJ',
    scopus_id: '36104666300',
    department: 'Geoinformatics',
  },
  {
    email: 'torsak.so@up.ac.th',
    name_en: 'Torsak Soontornphand',
    name_th: 'ต่อศักดิ์ สุนทรพันธุ์',
    position: 'อาจารย์',
    scholar_id: 'KDU_DD8AAAAJ',
    scopus_id: '57140709600',
    department: 'Geoinformatics',
  },
  {
    email: 'narongchai.mo@up.ac.th',
    name_en: 'Phuwissorn Phumsaranakhom',
    name_th: 'ภูวิศสรณ์ ภูมิสรณคมณ์',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57208544302',
    department: 'Geoinformatics',
  },
  {
    email: 'narasak.bo@up.ac.th',
    name_en: 'narasak boonthep',
    name_th: 'นราศักดิ์ บุญเทพ',
    position: 'อาจารย์',
    scholar_id: 'XmdKPOMAAAAJ',
    scopus_id: '55837732900',
    department: 'Geoinformatics',
  },
  {
    email: 'khomkris.ma@up.ac.th',
    name_en: 'Khomkris Mathiang',
    name_th: 'คมกริช มาเที่ยง',
    position: 'อาจารย์',
    scholar_id: 'wnvJ3JcAAAAJ',
    scopus_id: '24725258900',
    department: 'Geoinformatics',
  },
  {
    email: 'adisaya.ch@up.ac.th',
    name_en: 'Adisaya Charoenphol',
    name_th: 'อดิศยา เจริญผล',
    position: 'อาจารย์',
    scholar_id: 'iG8Tp28AAAAJ',
    scopus_id: '36809093400',
    department: 'Geoinformatics',
  },
  {
    email: 'wongpanya.nu@up.ac.th',
    name_en: '\'Wongpanya Nuankaew',
    name_th: 'วงษ์ปัญญา นวนแก้ว',
    position: 'ผู้ช่วยศาสตราจารย์ / ประธานหลักสูตร',
    scholar_id: 'pWRnha8AAAAJ',
    scopus_id: '57193735880',
    department: 'Computer Science',
  },
  {
    email: 'surangkana.ra@up.ac.th',
    name_en: '\'Surangkana Rawungyot',
    name_th: 'สุรางคนา ระวังยศ',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'ONrwXPcAAAAJ',
    scopus_id: '56247320800',
    department: 'Computer Science',
  },
  {
    email: 'worrakit.sa@up.ac.th',
    name_en: 'worrakit sanpote',
    name_th: 'วรกฤต แสนโภชน์',
    position: 'อาจารย์',
    scholar_id: 'd5XfUKoAAAAJ',
    scopus_id: null,
    department: 'Computer Science',
  },
  {
    email: 'thanawat.sa@up.ac.th',
    name_en: 'Thanawat Sae-eab',
    name_th: 'ธนวัฒน์ แซ่เอียบ',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Computer Science',
  },
  {
    email: 'kiattikul.so@up.ac.th',
    name_en: 'Kiattikul Suksomsathan',
    name_th: 'เกียรติกุล สุขสมสถาน',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '56109204000',
    department: 'Computer Science',
  },
  {
    email: 'thammarat.th@up.ac.th',
    name_en: 'Thammarat Thamma',
    name_th: 'ธรรมรัตน์ ธรรมา',
    position: 'อาจารย์',
    scholar_id: '-M6OQm4AAAAJ',
    scopus_id: null,
    department: 'Computer Science',
  },
  {
    email: 'paweena.un@up.ac.th',
    name_en: 'Paweena Unlee',
    name_th: 'ปวีณา อุ่นลี',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Computer Science',
  },
  {
    email: 'sarit.pr@up.ac.th',
    name_en: 'Sarit Promthep',
    name_th: 'ศริทธิ์ พร้อมเทพ',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Computer Science',
  },
  {
    email: 'sakpan.da@up.ac.th',
    name_en: 'Sakpan Dangmanee',
    name_th: 'ศักดิ์พันธุ์ แดงมณี',
    position: 'อาจารย์',
    scholar_id: 'AeOY2nYAAAAJ',
    scopus_id: '57223979059',
    department: 'Computer Science',
  },
  {
    email: 'noppadon.yo@up.ac.th',
    name_en: 'Noppadon Yosboonruang',
    name_th: 'นพดล ยศบุญเรือง',
    position: 'ผู้ช่วยศาสตราจารย์ / ประธานหลักสูตร',
    scholar_id: '2K_AJKUAAAAJ',
    scopus_id: null,
    department: 'Computer Science',
  },
  {
    email: 'kanokwatt.sh@up.ac.th',
    name_en: 'KANOKWATT SHIANGJEN',
    name_th: 'กนกวรรธน์ เซี่ยงเจ็น',
    position: 'อาจารย์',
    scholar_id: 'w2LATP4AAAAJ',
    scopus_id: '57120194100',
    department: 'Computer Science',
  },
  {
    email: 'sulawan.yo@up.ac.th',
    name_en: 'Sulawan Yotthanoo',
    name_th: 'สุลาวัลย์ ยศธนู',
    position: 'อาจารย์',
    scholar_id: 'oK0RgRcAAAAJ',
    scopus_id: null,
    department: 'Computer Science',
  },
  {
    email: 'kemmawadee.pr@up.ac.th',
    name_en: 'Kemmawadee Preedalikit',
    name_th: 'เขมวดี ปรีดาลิขิต',
    position: 'อาจารย์',
    scholar_id: 'CnkxqpgAAAAJ',
    scopus_id: null,
    department: 'Computer Science',
  },
  {
    email: 'piyada.ph@up.ac.th',
    name_en: 'Piyada Phrueksawatnon',
    name_th: 'ปิยดา พฤกสวัสดิ์นนท์',
    position: 'อาจารย์',
    scholar_id: 'vGckr9gAAAAJ',
    scopus_id: null,
    department: 'Computer Science',
  },
  {
    email: 'satsayamon.su@up.ac.th',
    name_en: 'satsayamon suksaengrakcharoen',
    name_th: 'ศัสยมน สุขแสงรักษ์เจริญ',
    position: 'อาจารย์',
    scholar_id: 'YgHiTT0AAAAJ',
    scopus_id: null,
    department: 'Computer Science',
  },
  {
    email: 'ruttana.ri@up.ac.th',
    name_en: 'Rattana Prommai',
    name_th: 'รัตนา พรมใหม่',
    position: 'อาจารย์',
    scholar_id: 'dorztZoAAAAJ',
    scopus_id: null,
    department: 'Computer Science',
  },
  {
    email: 'apiwat.wi@up.ac.th',
    name_en: 'Apiwat Wittayarat',
    name_th: 'อภิวัฒน์ วิทยารัฐ',
    position: 'ประธานหลักสูตร / อาจารย์',
    scholar_id: null,
    scopus_id: '57215270571',
    department: 'Computer Science',
  },
  {
    email: 'pornthep.ro@up.ac.th',
    name_en: 'Pornthep Rojanavasu',
    name_th: 'พรเทพ โรจนวสุ',
    position: 'ผู้ช่วยศาสตราจารย์ / คณบดี',
    scholar_id: 'pGxD1nkAAAAJ',
    scopus_id: '24464512600',
    department: 'Computer Science',
  },
  {
    email: 'jirabhorn.ch@up.ac.th',
    name_en: 'jirabhorn chaiwongsai',
    name_th: 'จิราพร ไชยวงศ์สาย',
    position: 'ผู้ช่วยศาสตราจารย์ / รองคณบดี',
    scholar_id: 'uSFP9soAAAAJ',
    scopus_id: '26643827900',
    department: 'Computer Science',
  },
  {
    email: 'bowonsak.sr@up.ac.th',
    name_en: 'Bowonsak Srisungsitthisanti',
    name_th: 'บวรศักดิ์ ศรีสังสิทธิสันติ',
    position: 'ผู้ช่วยศาสตราจารย์ / ผู้ช่วยคณบดี',
    scholar_id: 'AOHQFg8AAAAJ',
    scopus_id: '56021717400',
    department: 'Computer Science',
  },
  {
    email: 'sakorn.me@up.ac.th',
    name_en: 'Sakorn Mekruksavanich',
    name_th: 'สาคร เมฆรักษาวนิช',
    position: 'รองศาสตราจารย์',
    scholar_id: 'BElkl-MAAAAJ',
    scopus_id: '35174894700',
    department: 'Computer Science',
  },
  {
    email: 'thana.ud@up.ac.th',
    name_en: 'Thana Udomsripaiboon',
    name_th: 'ธนา อุดมศรีไพบูลย์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'HAAwwFIAAAAJ',
    scopus_id: '15926581200',
    department: 'Computer Science',
  },
  {
    email: 'wattanapong.su@up.ac.th',
    name_en: 'Wattanapong Suttapak',
    name_th: 'วัฒนพงศ์ สุทธภักดิ์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'A0mVNt4AAAAJ',
    scopus_id: '36104666300',
    department: 'Computer Science',
  },
  {
    email: 'torsak.so@up.ac.th',
    name_en: 'Torsak Soontornphand',
    name_th: 'ต่อศักดิ์ สุนทรพันธุ์',
    position: 'อาจารย์',
    scholar_id: 'KDU_DD8AAAAJ',
    scopus_id: '57140709600',
    department: 'Computer Science',
  },
  {
    email: 'narongchai.mo@up.ac.th',
    name_en: 'Phuwissorn Phumsaranakhom',
    name_th: 'ภูวิศสรณ์ ภูมิสรณคมณ์',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57208544302',
    department: 'Computer Science',
  },
  {
    email: 'narasak.bo@up.ac.th',
    name_en: 'narasak boonthep',
    name_th: 'นราศักดิ์ บุญเทพ',
    position: 'อาจารย์',
    scholar_id: 'XmdKPOMAAAAJ',
    scopus_id: '55837732900',
    department: 'Computer Science',
  },
  {
    email: 'khomkris.ma@up.ac.th',
    name_en: 'Khomkris Mathiang',
    name_th: 'คมกริช มาเที่ยง',
    position: 'อาจารย์',
    scholar_id: 'wnvJ3JcAAAAJ',
    scopus_id: '24725258900',
    department: 'Computer Science',
  },
  {
    email: 'adisaya.ch@up.ac.th',
    name_en: 'Adisaya Charoenphol',
    name_th: 'อดิศยา เจริญผล',
    position: 'อาจารย์',
    scholar_id: 'iG8Tp28AAAAJ',
    scopus_id: '36809093400',
    department: 'Computer Science',
  },
  {
    email: 'nattapon.ha@up.ac.th',
    name_en: 'Nattapon Harnsamut',
    name_th: 'ณัฐพล หาญสมุทร',
    position: 'ประธานหลักสูตร / อาจารย์',
    scholar_id: '0wUVQkYAAAAJ',
    scopus_id: '25960063900',
    department: 'Computer Science',
  },
  {
    email: 'davit.sa@up.ac.th',
    name_en: 'davit sanpote',
    name_th: 'ดวิษ แสนโภชน์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: '5YhyT8AAAAAJ',
    scopus_id: '57194212031',
    department: 'Computer Science',
  },
  {
    email: 'apiwat.bu@up.ac.th',
    name_en: 'Apiwat Budwong',
    name_th: 'อภิวัฒน์ บุตรวงค์',
    position: 'อาจารย์',
    scholar_id: 'P_PFNCAAAAAJ',
    scopus_id: '57226400625',
    department: 'Computer Science',
  },
  {
    email: 'sujittra.sa@up.ac.th',
    name_en: 'Sujittra Inmanee',
    name_th: 'สุจิตตรา อินมะณี',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Computer Science',
  },
  {
    email: 'chaow.po@up.ac.th',
    name_en: 'Chaow Pokaew',
    name_th: 'เชาวน์ ปอแก้ว',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57202941427',
    department: 'Computer Science',
  },
  {
    email: 'chontipan.pl@up.ac.th',
    name_en: 'Chontipan Plengwitthaya',
    name_th: 'ชลติพันธ์ เปล่งวิทยา',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57202948923',
    department: 'Computer Science',
  },
  {
    email: 'mathaya.ra@up.ac.th',
    name_en: 'Mathaya Ratchakhom',
    name_th: 'เมธยา ราชคมน์',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '43261601400',
    department: 'Computer Science',
  },
  {
    email: 'noppadon.yo@up.ac.th',
    name_en: 'Noppadon Yosboonruang',
    name_th: 'นพดล ยศบุญเรือง',
    position: 'ผู้ช่วยศาสตราจารย์ / ประธานหลักสูตร',
    scholar_id: '2K_AJKUAAAAJ',
    scopus_id: null,
    department: 'Data Science and Applications',
  },
  {
    email: 'kanokwatt.sh@up.ac.th',
    name_en: 'KANOKWATT SHIANGJEN',
    name_th: 'กนกวรรธน์ เซี่ยงเจ็น',
    position: 'อาจารย์',
    scholar_id: 'w2LATP4AAAAJ',
    scopus_id: '57120194100',
    department: 'Data Science and Applications',
  },
  {
    email: 'sulawan.yo@up.ac.th',
    name_en: 'Sulawan Yotthanoo',
    name_th: 'สุลาวัลย์ ยศธนู',
    position: 'อาจารย์',
    scholar_id: 'oK0RgRcAAAAJ',
    scopus_id: null,
    department: 'Data Science and Applications',
  },
  {
    email: 'kemmawadee.pr@up.ac.th',
    name_en: 'Kemmawadee Preedalikit',
    name_th: 'เขมวดี ปรีดาลิขิต',
    position: 'อาจารย์',
    scholar_id: 'CnkxqpgAAAAJ',
    scopus_id: null,
    department: 'Data Science and Applications',
  },
  {
    email: 'piyada.ph@up.ac.th',
    name_en: 'Piyada Phrueksawatnon',
    name_th: 'ปิยดา พฤกสวัสดิ์นนท์',
    position: 'อาจารย์',
    scholar_id: 'vGckr9gAAAAJ',
    scopus_id: null,
    department: 'Data Science and Applications',
  },
  {
    email: 'satsayamon.su@up.ac.th',
    name_en: 'satsayamon suksaengrakcharoen',
    name_th: 'ศัสยมน สุขแสงรักษ์เจริญ',
    position: 'อาจารย์',
    scholar_id: 'YgHiTT0AAAAJ',
    scopus_id: null,
    department: 'Data Science and Applications',
  },
  {
    email: 'ruttana.ri@up.ac.th',
    name_en: 'Rattana Prommai',
    name_th: 'รัตนา พรมใหม่',
    position: 'อาจารย์',
    scholar_id: 'dorztZoAAAAJ',
    scopus_id: null,
    department: 'Data Science and Applications',
  },
  {
    email: 'apiwat.wi@up.ac.th',
    name_en: 'Apiwat Wittayarat',
    name_th: 'อภิวัฒน์ วิทยารัฐ',
    position: 'ประธานหลักสูตร / อาจารย์',
    scholar_id: null,
    scopus_id: '57215270571',
    department: 'Data Science and Applications',
  },
  {
    email: 'pornthep.ro@up.ac.th',
    name_en: 'Pornthep Rojanavasu',
    name_th: 'พรเทพ โรจนวสุ',
    position: 'ผู้ช่วยศาสตราจารย์ / คณบดี',
    scholar_id: 'pGxD1nkAAAAJ',
    scopus_id: '24464512600',
    department: 'Data Science and Applications',
  },
  {
    email: 'jirabhorn.ch@up.ac.th',
    name_en: 'jirabhorn chaiwongsai',
    name_th: 'จิราพร ไชยวงศ์สาย',
    position: 'ผู้ช่วยศาสตราจารย์ / รองคณบดี',
    scholar_id: 'uSFP9soAAAAJ',
    scopus_id: '26643827900',
    department: 'Data Science and Applications',
  },
  {
    email: 'bowonsak.sr@up.ac.th',
    name_en: 'Bowonsak Srisungsitthisanti',
    name_th: 'บวรศักดิ์ ศรีสังสิทธิสันติ',
    position: 'ผู้ช่วยศาสตราจารย์ / ผู้ช่วยคณบดี',
    scholar_id: 'AOHQFg8AAAAJ',
    scopus_id: '56021717400',
    department: 'Data Science and Applications',
  },
  {
    email: 'sakorn.me@up.ac.th',
    name_en: 'Sakorn Mekruksavanich',
    name_th: 'สาคร เมฆรักษาวนิช',
    position: 'รองศาสตราจารย์',
    scholar_id: 'BElkl-MAAAAJ',
    scopus_id: '35174894700',
    department: 'Data Science and Applications',
  },
  {
    email: 'thana.ud@up.ac.th',
    name_en: 'Thana Udomsripaiboon',
    name_th: 'ธนา อุดมศรีไพบูลย์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'HAAwwFIAAAAJ',
    scopus_id: '15926581200',
    department: 'Data Science and Applications',
  },
  {
    email: 'wattanapong.su@up.ac.th',
    name_en: 'Wattanapong Suttapak',
    name_th: 'วัฒนพงศ์ สุทธภักดิ์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'A0mVNt4AAAAJ',
    scopus_id: '36104666300',
    department: 'Data Science and Applications',
  },
  {
    email: 'torsak.so@up.ac.th',
    name_en: 'Torsak Soontornphand',
    name_th: 'ต่อศักดิ์ สุนทรพันธุ์',
    position: 'อาจารย์',
    scholar_id: 'KDU_DD8AAAAJ',
    scopus_id: '57140709600',
    department: 'Data Science and Applications',
  },
  {
    email: 'narongchai.mo@up.ac.th',
    name_en: 'Phuwissorn Phumsaranakhom',
    name_th: 'ภูวิศสรณ์ ภูมิสรณคมณ์',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57208544302',
    department: 'Data Science and Applications',
  },
  {
    email: 'narasak.bo@up.ac.th',
    name_en: 'narasak boonthep',
    name_th: 'นราศักดิ์ บุญเทพ',
    position: 'อาจารย์',
    scholar_id: 'XmdKPOMAAAAJ',
    scopus_id: '55837732900',
    department: 'Data Science and Applications',
  },
  {
    email: 'khomkris.ma@up.ac.th',
    name_en: 'Khomkris Mathiang',
    name_th: 'คมกริช มาเที่ยง',
    position: 'อาจารย์',
    scholar_id: 'wnvJ3JcAAAAJ',
    scopus_id: '24725258900',
    department: 'Data Science and Applications',
  },
  {
    email: 'adisaya.ch@up.ac.th',
    name_en: 'Adisaya Charoenphol',
    name_th: 'อดิศยา เจริญผล',
    position: 'อาจารย์',
    scholar_id: 'iG8Tp28AAAAJ',
    scopus_id: '36809093400',
    department: 'Data Science and Applications',
  },
  {
    email: 'nattapon.ha@up.ac.th',
    name_en: 'Nattapon Harnsamut',
    name_th: 'ณัฐพล หาญสมุทร',
    position: 'ประธานหลักสูตร / อาจารย์',
    scholar_id: '0wUVQkYAAAAJ',
    scopus_id: '25960063900',
    department: 'Data Science and Applications',
  },
  {
    email: 'davit.sa@up.ac.th',
    name_en: 'davit sanpote',
    name_th: 'ดวิษ แสนโภชน์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: '5YhyT8AAAAAJ',
    scopus_id: '57194212031',
    department: 'Data Science and Applications',
  },
  {
    email: 'apiwat.bu@up.ac.th',
    name_en: 'Apiwat Budwong',
    name_th: 'อภิวัฒน์ บุตรวงค์',
    position: 'อาจารย์',
    scholar_id: 'P_PFNCAAAAAJ',
    scopus_id: '57226400625',
    department: 'Data Science and Applications',
  },
  {
    email: 'sujittra.sa@up.ac.th',
    name_en: 'Sujittra Inmanee',
    name_th: 'สุจิตตรา อินมะณี',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Data Science and Applications',
  },
  {
    email: 'chaow.po@up.ac.th',
    name_en: 'Chaow Pokaew',
    name_th: 'เชาวน์ ปอแก้ว',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57202941427',
    department: 'Data Science and Applications',
  },
  {
    email: 'chontipan.pl@up.ac.th',
    name_en: 'Chontipan Plengwitthaya',
    name_th: 'ชลติพันธ์ เปล่งวิทยา',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57202948923',
    department: 'Data Science and Applications',
  },
  {
    email: 'mathaya.ra@up.ac.th',
    name_en: 'Mathaya Ratchakhom',
    name_th: 'เมธยา ราชคมน์',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '43261601400',
    department: 'Data Science and Applications',
  },
  {
    email: 'apiwat.wi@up.ac.th',
    name_en: 'Apiwat Wittayarat',
    name_th: 'อภิวัฒน์ วิทยารัฐ',
    position: 'ประธานหลักสูตร / อาจารย์',
    scholar_id: null,
    scopus_id: '57215270571',
    department: 'Computer Engineering',
  },
  {
    email: 'pornthep.ro@up.ac.th',
    name_en: 'Pornthep Rojanavasu',
    name_th: 'พรเทพ โรจนวสุ',
    position: 'ผู้ช่วยศาสตราจารย์ / คณบดี',
    scholar_id: 'pGxD1nkAAAAJ',
    scopus_id: '24464512600',
    department: 'Computer Engineering',
  },
  {
    email: 'jirabhorn.ch@up.ac.th',
    name_en: 'jirabhorn chaiwongsai',
    name_th: 'จิราพร ไชยวงศ์สาย',
    position: 'ผู้ช่วยศาสตราจารย์ / รองคณบดี',
    scholar_id: 'uSFP9soAAAAJ',
    scopus_id: '26643827900',
    department: 'Computer Engineering',
  },
  {
    email: 'bowonsak.sr@up.ac.th',
    name_en: 'Bowonsak Srisungsitthisanti',
    name_th: 'บวรศักดิ์ ศรีสังสิทธิสันติ',
    position: 'ผู้ช่วยศาสตราจารย์ / ผู้ช่วยคณบดี',
    scholar_id: 'AOHQFg8AAAAJ',
    scopus_id: '56021717400',
    department: 'Computer Engineering',
  },
  {
    email: 'sakorn.me@up.ac.th',
    name_en: 'Sakorn Mekruksavanich',
    name_th: 'สาคร เมฆรักษาวนิช',
    position: 'รองศาสตราจารย์',
    scholar_id: 'BElkl-MAAAAJ',
    scopus_id: '35174894700',
    department: 'Computer Engineering',
  },
  {
    email: 'thana.ud@up.ac.th',
    name_en: 'Thana Udomsripaiboon',
    name_th: 'ธนา อุดมศรีไพบูลย์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'HAAwwFIAAAAJ',
    scopus_id: '15926581200',
    department: 'Computer Engineering',
  },
  {
    email: 'wattanapong.su@up.ac.th',
    name_en: 'Wattanapong Suttapak',
    name_th: 'วัฒนพงศ์ สุทธภักดิ์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: 'A0mVNt4AAAAJ',
    scopus_id: '36104666300',
    department: 'Computer Engineering',
  },
  {
    email: 'torsak.so@up.ac.th',
    name_en: 'Torsak Soontornphand',
    name_th: 'ต่อศักดิ์ สุนทรพันธุ์',
    position: 'อาจารย์',
    scholar_id: 'KDU_DD8AAAAJ',
    scopus_id: '57140709600',
    department: 'Computer Engineering',
  },
  {
    email: 'narongchai.mo@up.ac.th',
    name_en: 'Phuwissorn Phumsaranakhom',
    name_th: 'ภูวิศสรณ์ ภูมิสรณคมณ์',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57208544302',
    department: 'Computer Engineering',
  },
  {
    email: 'narasak.bo@up.ac.th',
    name_en: 'narasak boonthep',
    name_th: 'นราศักดิ์ บุญเทพ',
    position: 'อาจารย์',
    scholar_id: 'XmdKPOMAAAAJ',
    scopus_id: '55837732900',
    department: 'Computer Engineering',
  },
  {
    email: 'khomkris.ma@up.ac.th',
    name_en: 'Khomkris Mathiang',
    name_th: 'คมกริช มาเที่ยง',
    position: 'อาจารย์',
    scholar_id: 'wnvJ3JcAAAAJ',
    scopus_id: '24725258900',
    department: 'Computer Engineering',
  },
  {
    email: 'adisaya.ch@up.ac.th',
    name_en: 'Adisaya Charoenphol',
    name_th: 'อดิศยา เจริญผล',
    position: 'อาจารย์',
    scholar_id: 'iG8Tp28AAAAJ',
    scopus_id: '36809093400',
    department: 'Computer Engineering',
  },
  {
    email: 'nattapon.ha@up.ac.th',
    name_en: 'Nattapon Harnsamut',
    name_th: 'ณัฐพล หาญสมุทร',
    position: 'ประธานหลักสูตร / อาจารย์',
    scholar_id: '0wUVQkYAAAAJ',
    scopus_id: '25960063900',
    department: 'Computer Engineering',
  },
  {
    email: 'davit.sa@up.ac.th',
    name_en: 'davit sanpote',
    name_th: 'ดวิษ แสนโภชน์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: '5YhyT8AAAAAJ',
    scopus_id: '57194212031',
    department: 'Computer Engineering',
  },
  {
    email: 'apiwat.bu@up.ac.th',
    name_en: 'Apiwat Budwong',
    name_th: 'อภิวัฒน์ บุตรวงค์',
    position: 'อาจารย์',
    scholar_id: 'P_PFNCAAAAAJ',
    scopus_id: '57226400625',
    department: 'Computer Engineering',
  },
  {
    email: 'sujittra.sa@up.ac.th',
    name_en: 'Sujittra Inmanee',
    name_th: 'สุจิตตรา อินมะณี',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Computer Engineering',
  },
  {
    email: 'chaow.po@up.ac.th',
    name_en: 'Chaow Pokaew',
    name_th: 'เชาวน์ ปอแก้ว',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57202941427',
    department: 'Computer Engineering',
  },
  {
    email: 'chontipan.pl@up.ac.th',
    name_en: 'Chontipan Plengwitthaya',
    name_th: 'ชลติพันธ์ เปล่งวิทยา',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57202948923',
    department: 'Computer Engineering',
  },
  {
    email: 'mathaya.ra@up.ac.th',
    name_en: 'Mathaya Ratchakhom',
    name_th: 'เมธยา ราชคมน์',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '43261601400',
    department: 'Computer Engineering',
  },
  {
    email: 'nattapon.ha@up.ac.th',
    name_en: 'Nattapon Harnsamut',
    name_th: 'ณัฐพล หาญสมุทร',
    position: 'ประธานหลักสูตร / อาจารย์',
    scholar_id: '0wUVQkYAAAAJ',
    scopus_id: '25960063900',
    department: 'Software Engineering',
  },
  {
    email: 'davit.sa@up.ac.th',
    name_en: 'davit sanpote',
    name_th: 'ดวิษ แสนโภชน์',
    position: 'ผู้ช่วยศาสตราจารย์',
    scholar_id: '5YhyT8AAAAAJ',
    scopus_id: '57194212031',
    department: 'Software Engineering',
  },
  {
    email: 'apiwat.bu@up.ac.th',
    name_en: 'Apiwat Budwong',
    name_th: 'อภิวัฒน์ บุตรวงค์',
    position: 'อาจารย์',
    scholar_id: 'P_PFNCAAAAAJ',
    scopus_id: '57226400625',
    department: 'Software Engineering',
  },
  {
    email: 'sujittra.sa@up.ac.th',
    name_en: 'Sujittra Inmanee',
    name_th: 'สุจิตตรา อินมะณี',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: null,
    department: 'Software Engineering',
  },
  {
    email: 'chaow.po@up.ac.th',
    name_en: 'Chaow Pokaew',
    name_th: 'เชาวน์ ปอแก้ว',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57202941427',
    department: 'Software Engineering',
  },
  {
    email: 'chontipan.pl@up.ac.th',
    name_en: 'Chontipan Plengwitthaya',
    name_th: 'ชลติพันธ์ เปล่งวิทยา',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '57202948923',
    department: 'Software Engineering',
  },
  {
    email: 'mathaya.ra@up.ac.th',
    name_en: 'Mathaya Ratchakhom',
    name_th: 'เมธยา ราชคมน์',
    position: 'อาจารย์',
    scholar_id: null,
    scopus_id: '43261601400',
    department: 'Software Engineering',
  }
];
export default UP_ICT_FACULTY;
